# Generated by Django 5.1.1 on 2024-09-06 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTPModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=255, unique=True)),
                ('latest_otp', models.CharField(max_length=4)),
            ],
        ),
    ]
