# Generated by Django 5.1.1 on 2024-09-06 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otpmodel',
            old_name='latest_otp',
            new_name='otp',
        ),
    ]
