# Generated by Django 5.1.1 on 2024-09-06 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_otpmodel_otp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otpmodel',
            old_name='otp',
            new_name='latest_otp',
        ),
    ]
